In [ ]:
import tensorflow as tf

In [ ]:
# tf.constant로 텐서를 만들 수 있음
# Tensor -> 데이터의 배열 / 0차원 scalar, 1차원  vertor, 2차원 matrix, 3차원  3d-tensor, 4차원 4d-tensor
scalar = tf.constant(42)
matrix = tf.constant([[1, 2, 3], [4,5,6]], dtype=float)
vector = tf.constant([1,2,3,4])
_3d_tensor = tf.constant([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])

In [ ]:
print(scalar)
print(vector)
print(matrix)
print(_3d_tensor)

tf.Tensor(42, shape=(), dtype=int32)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]], shape=(3, 3, 3), dtype=int32)


In [ ]:
# shape
scalar.shape

TensorShape([])

In [ ]:
vector.shape

TensorShape([4])

In [ ]:
matrix.shape

TensorShape([2, 3])

In [ ]:
_3d_tensor.shape

TensorShape([3, 3, 3])

In [ ]:
# indexing and slicing
vector[:2]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [ ]:
matrix[1,1]

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

In [ ]:
_3d_tensor[2, 2, 2]

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [ ]:
# numpy array에서 되는 연산 대부분이 가능합니다
scalar + 100

<tf.Tensor: shape=(), dtype=int32, numpy=142>

In [ ]:
matrix + 10 # broadcasting

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [ ]:
tf.square(matrix) 

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [ ]:
tf.transpose(matrix)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 4.],
       [2., 5.],
       [3., 6.]], dtype=float32)>

In [ ]:
# 축 추가 
tensor_1 = _3d_tensor[tf.newaxis, ...]
tensor_1.shape

TensorShape([1, 3, 3, 3])

In [ ]:
# 축 제거 -> 축소
tensor_2 = tf.squeeze(tensor_1)
tensor_2.shape

TensorShape([3, 3, 3])

In [ ]:
# 평균
tf.reduce_mean(matrix)

<tf.Tensor: shape=(), dtype=float32, numpy=3.5>

In [ ]:
# 합
tf.reduce_sum(matrix)

<tf.Tensor: shape=(), dtype=float32, numpy=21.0>

In [ ]:
# 최댓값
tf.reduce_max(matrix)

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [ ]:
# 최솟값
tf.reduce_min(matrix)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [ ]:
import numpy as np

In [ ]:
# numpy tensor를 만들거나 tensor를 numpy로 변환 가능
arr = np.array([[1,2,3,4,5]])
tensor = tf.constant(arr)
tensor

<tf.Tensor: shape=(1, 5), dtype=int64, numpy=array([[1, 2, 3, 4, 5]])>

In [ ]:
arr2 = tensor.numpy()
arr2

array([[1, 2, 3, 4, 5]])

In [ ]:
# type 변환
# error 발생
tf.constant(1) + tf.constant(1.)

InvalidArgumentError: ignored

In [ ]:
con_1 = tf.constant(1)
con_2 = tf.constant(1.)

con_1 = tf.cast(con_1, tf.float32)
con_1 + con_2 

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [ ]:
# 변수
var = tf.Variable(tensor)
var

<tf.Variable 'Variable:0' shape=(1, 5) dtype=int64, numpy=array([[1, 2, 3, 4, 5]])>

In [ ]:
tensor[0,0] = 1 * 2

TypeError: ignored

In [ ]:
var[0, 0].assign(2)

<tf.Variable 'UnreadVariable' shape=(1, 5) dtype=int64, numpy=array([[2, 2, 3, 4, 5]])>

In [ ]:
id(con_1)

140214240847056